### ISSUE TITLE
why? detail motivation for project

### ISSUE THREAD

**Issue by jpritikin** [CryptoverseCC/ethmail.cc#1]
This seems like a good idea, but it would help to add a list of motivations somewhere. Why should I route my email through ethmail?

**Comment by gkapkowski** [comment]
Excellent question! 

The short answer is that world where there is nothing like ETHMail didn't make sense to me.

I wanted to allow people to reach out even in situation where all they have is the other person ethereum address.
Imagine when you browse etherscan or look at some dapp, you can find interesting address doing interesting stuff, eg. deploying smart contracts that look exactly like what you wanted to do, or owning the one NFT token that you just need to have but can't find it on any auction, etc.
There is no guarantee that the other person is using ETHMail and that they will see your message but you CAN leave them a message. When they decide to login for the first time, your message will be waiting for them.

This was my main motivation, enable communication between people who found each other on the blockchain.  

My other motivations were more esoteric:
- NFTs mailboxes - mailbox that is accessible only to given token owner
- Token Newsletters - community newsletter available to owners of certain tokens.
- Spam filtering - filter incoming messages by sender token ownership and history of transactions

I also wanted to use existing technologies, so that ETHMail is compatible with what people currently use.

There is also cryptoauth.io. When implementing Open ID Connect protocol I needed to provide user email, this email would be used by already existing products and software. It had to be compatible with what email is currently. Since Cryptoauth uses Ethereum address as identity and doesn't require users to "register" anywhere, ETHMail also had to work like this.

And to directly answer you question "Why should I route my email through ethmail?". Please don't. Don't use ETHMail as if it was your (you as a person) email. 
Use it as a gateway that people can use to contact you without reviling yourself. You can import all email coming to ETHMail to your normal email account and use it from email clients you already use (I use ETHMail account with my Gmail mobile app)
Use ETHMail when you need to send email to someone "outside" (eg. to someone@gmail.com) to prove that you control given address. It should be simpler than sending them signed messages and expecting them to verify on their own that the signature is valid and coming from the right address.

I also hope that Dapps will stop asking people about their real-life emails just because they want to send them marketing information.

**Comment by jpritikin** [comment]
> There is no guarantee that the other person is using ETHMail and that they will see your message but you CAN leave them a message. When they decide to login for the first time, your message will be waiting for them.

Where is the message waiting? On your server? How much compute/storage resource does it take you to run this service? Do you have any plan to make this self sustaining?

> I also hope that Dapps will stop asking people about their real-life emails just because they want to send them marketing information.

Yeah, cool

> Spam filtering - filter incoming messages by sender token ownership and history of transactions

This is what got me excited when Vitalik wrote about this a few years ago. You haven't implemented any of these options yet?

> Excellent question!

Maybe you could add a FAQ to the https://ethmail.cc/ webpage?

**Comment by gkapkowski** [comment]
> Where is the message waiting? On your server?
Yes, ETHMail in it's core is just a normal email server.

> How much compute/storage resource does it take you to run this service? 
~150$ a month currently  

> Do you have any plan to make this self sustaining?
Yes ;) 

> This is what got me excited when Vitalik wrote about this a few years ago. You haven't implemented any of these options yet?
Not yet, if you don't mind would you share your idea on how it should work? I'm gathering requirements for this feature.

> Maybe you could add a FAQ to the https://ethmail.cc/ webpage?
I really should, just need to find time to do it.

**Comment by jpritikin** [comment]
> > Spam filtering - filter incoming messages by sender token ownership and history of transactions

> Not yet, if you don't mind would you share your idea on how it should work? I'm gathering requirements for this feature.

I'm not sure. I've been using pobox.com to receive email and they seem to have pretty good spam filtering. Spam is no longer a raging dumpster fire; I haven't thought about it much recently.

If I recall correctly, Vitalik's idea was for senders to post a security deposit that can be burned by receivers. I pay pobox 50 USD per year so the question is how to reach a similar level of affordability. One way that pobox reduces friction is to automatically whitelist correspondents and apply spam filters only to addresses that my account hasn't seen before. Well, if you study the area, you will probably have more ideas than me. That's all I can think of for now.

Anyway, I think you have a cool project; I'll keep an eye on your progress.
